/*
 * generated by Xtext
 */
package org.eclipse.docker.language.ui.contentassist

import org.eclipse.docker.language.ui.contentassist.AbstractContainerProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ContainerProposalProvider extends AbstractContainerProposalProvider {
}
