/*
 * generated by Xtext
 */
package org.eclipse.docker.language;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ContainerUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.eclipse.docker.language.ui.internal.ContainerActivator.getInstance().getInjector("org.eclipse.docker.language.Container");
	}
	
}
