/*
 * generated by Xtext
 */
package org.eclipse.docker.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ContainerRuntimeModule extends org.eclipse.docker.language.AbstractContainerRuntimeModule {

}
