/*
 * generated by Xtext
 */
package org.eclipse.docker.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ContainerStandaloneSetup extends ContainerStandaloneSetupGenerated{

	public static void doSetup() {
		new ContainerStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

