/*
 * generated by Xtext
 */
package org.eclipse.docker.language.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractContainerValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.eclipse.docker.language.container.ContainerPackage.eINSTANCE);
		return result;
	}
}
