/*
 * generated by Xtext
 */
package org.eclipse.docker.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ContainerUiModule extends org.eclipse.docker.language.ui.AbstractContainerUiModule {
	public ContainerUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
