/*
 * generated by Xtext
 */
package org.eclipse.docker.language.ui;

import org.eclipse.docker.language.launch.DockerConsole;
import org.eclipse.ui.plugin.AbstractUIPlugin;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ContainerUiModule extends org.eclipse.docker.language.ui.AbstractContainerUiModule {
	public ContainerUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	@Override
	public void configure(Binder binder) {
		
		super.configure(binder);
	}
}
