/*
 * generated by Xtext
 */
grammar InternalContainer;

options {
	superClass=AbstractInternalAntlrParser;
	
}

@lexer::header {
package org.eclipse.docker.language.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.eclipse.docker.language.parser.antlr.internal; 

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.eclipse.docker.language.services.ContainerGrammarAccess;

}

@parser::members {

 	private ContainerGrammarAccess grammarAccess;
 	
    public InternalContainerParser(TokenStream input, ContainerGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }
    
    @Override
    protected String getFirstRuleName() {
    	return "Docker";	
   	}
   	
   	@Override
   	protected ContainerGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}
}

@rulecatch { 
    catch (RecognitionException re) { 
        recover(input,re); 
        appendSkippedTokens();
    } 
}




// Entry rule entryRuleDocker
entryRuleDocker returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getDockerRule()); }
	 iv_ruleDocker=ruleDocker 
	 { $current=$iv_ruleDocker.current; } 
	 EOF 
;

// Rule Docker
ruleDocker returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
((
(
		{ 
	        newCompositeNode(grammarAccess.getDockerAccess().getContainersContainerParserRuleCall_0_0()); 
	    }
		lv_containers_0_0=ruleContainer		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getDockerRule());
	        }
       		add(
       			$current, 
       			"containers",
        		lv_containers_0_0, 
        		"org.eclipse.docker.language.Container.Container");
	        afterParserOrEnumRuleCall();
	    }

)
)
    |(
(
		{ 
	        newCompositeNode(grammarAccess.getDockerAccess().getImagesImageParserRuleCall_1_0()); 
	    }
		lv_images_1_0=ruleImage		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getDockerRule());
	        }
       		add(
       			$current, 
       			"images",
        		lv_images_1_0, 
        		"org.eclipse.docker.language.Container.Image");
	        afterParserOrEnumRuleCall();
	    }

)
))*
;





// Entry rule entryRuleImage
entryRuleImage returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getImageRule()); }
	 iv_ruleImage=ruleImage 
	 { $current=$iv_ruleImage.current; } 
	 EOF 
;

// Rule Image
ruleImage returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='image' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getImageAccess().getImageKeyword_0());
    }
(
(
		lv_name_1_0=RULE_STRING
		{
			newLeafNode(lv_name_1_0, grammarAccess.getImageAccess().getNameSTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getImageRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)	otherlv_2='{' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getImageAccess().getLeftCurlyBracketKeyword_2());
    }
(

(
	{ 
	  getUnorderedGroupHelper().enter(grammarAccess.getImageAccess().getUnorderedGroup_3());
	}
	(
		(

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getImageAccess().getUnorderedGroup_3(), 0)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getImageAccess().getUnorderedGroup_3(), 0);
	 				}
					({true}?=>(	otherlv_4='tag' 
    {
    	newLeafNode(otherlv_4, grammarAccess.getImageAccess().getTagKeyword_3_0_0());
    }
(
(
		lv_tag_5_0=RULE_STRING
		{
			newLeafNode(lv_tag_5_0, grammarAccess.getImageAccess().getTagSTRINGTerminalRuleCall_3_0_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getImageRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"tag",
        		lv_tag_5_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getImageAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getImageAccess().getUnorderedGroup_3(), 1)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getImageAccess().getUnorderedGroup_3(), 1);
	 				}
					({true}?=>(	otherlv_6='dockerFileLocation' 
    {
    	newLeafNode(otherlv_6, grammarAccess.getImageAccess().getDockerFileLocationKeyword_3_1_0());
    }
(
(
		lv_dockerFilelocation_7_0=RULE_STRING
		{
			newLeafNode(lv_dockerFilelocation_7_0, grammarAccess.getImageAccess().getDockerFilelocationSTRINGTerminalRuleCall_3_1_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getImageRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"dockerFilelocation",
        		lv_dockerFilelocation_7_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getImageAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getImageAccess().getUnorderedGroup_3(), 2)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getImageAccess().getUnorderedGroup_3(), 2);
	 				}
					({true}?=>(	otherlv_8='buildArg' 
    {
    	newLeafNode(otherlv_8, grammarAccess.getImageAccess().getBuildArgKeyword_3_2_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getImageAccess().getBuildargsBuildArgsParserRuleCall_3_2_1_0()); 
	    }
		lv_buildargs_9_0=ruleBuildArgs		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getImageRule());
	        }
       		set(
       			$current, 
       			"buildargs",
        		lv_buildargs_9_0, 
        		"org.eclipse.docker.language.Container.BuildArgs");
	        afterParserOrEnumRuleCall();
	    }

)
)+))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getImageAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getImageAccess().getUnorderedGroup_3(), 3)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getImageAccess().getUnorderedGroup_3(), 3);
	 				}
					({true}?=>(	otherlv_10='noCache' 
    {
    	newLeafNode(otherlv_10, grammarAccess.getImageAccess().getNoCacheKeyword_3_3_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getImageAccess().getNoCacheEBooleanParserRuleCall_3_3_1_0()); 
	    }
		lv_noCache_11_0=ruleEBoolean		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getImageRule());
	        }
       		set(
       			$current, 
       			"noCache",
        		lv_noCache_11_0, 
        		"org.eclipse.docker.language.Container.EBoolean");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getImageAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getImageAccess().getUnorderedGroup_3(), 4)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getImageAccess().getUnorderedGroup_3(), 4);
	 				}
					({true}?=>(	otherlv_12='memory' 
    {
    	newLeafNode(otherlv_12, grammarAccess.getImageAccess().getMemoryKeyword_3_4_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getImageAccess().getMemoryElongParserRuleCall_3_4_1_0()); 
	    }
		lv_memory_13_0=ruleElong		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getImageRule());
	        }
       		set(
       			$current, 
       			"memory",
        		lv_memory_13_0, 
        		"org.eclipse.docker.language.Container.Elong");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getImageAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getImageAccess().getUnorderedGroup_3(), 5)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getImageAccess().getUnorderedGroup_3(), 5);
	 				}
					({true}?=>(	otherlv_14='memswap' 
    {
    	newLeafNode(otherlv_14, grammarAccess.getImageAccess().getMemswapKeyword_3_5_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getImageAccess().getMemswapElongParserRuleCall_3_5_1_0()); 
	    }
		lv_memswap_15_0=ruleElong		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getImageRule());
	        }
       		set(
       			$current, 
       			"memswap",
        		lv_memswap_15_0, 
        		"org.eclipse.docker.language.Container.Elong");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getImageAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getImageAccess().getUnorderedGroup_3(), 6)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getImageAccess().getUnorderedGroup_3(), 6);
	 				}
					({true}?=>(	otherlv_16='cpusetcpus' 
    {
    	newLeafNode(otherlv_16, grammarAccess.getImageAccess().getCpusetcpusKeyword_3_6_0());
    }
(
(
		lv_cpusetcpus_17_0=RULE_STRING
		{
			newLeafNode(lv_cpusetcpus_17_0, grammarAccess.getImageAccess().getCpusetcpusSTRINGTerminalRuleCall_3_6_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getImageRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"cpusetcpus",
        		lv_cpusetcpus_17_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getImageAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getImageAccess().getUnorderedGroup_3(), 7)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getImageAccess().getUnorderedGroup_3(), 7);
	 				}
					({true}?=>(	otherlv_18='cpushares' 
    {
    	newLeafNode(otherlv_18, grammarAccess.getImageAccess().getCpusharesKeyword_3_7_0());
    }
(
(
		lv_cpushares_19_0=RULE_STRING
		{
			newLeafNode(lv_cpushares_19_0, grammarAccess.getImageAccess().getCpusharesSTRINGTerminalRuleCall_3_7_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getImageRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"cpushares",
        		lv_cpushares_19_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getImageAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getImageAccess().getUnorderedGroup_3(), 8)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getImageAccess().getUnorderedGroup_3(), 8);
	 				}
					({true}?=>(	otherlv_20='remove' 
    {
    	newLeafNode(otherlv_20, grammarAccess.getImageAccess().getRemoveKeyword_3_8_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getImageAccess().getRemoveEBooleanParserRuleCall_3_8_1_0()); 
	    }
		lv_remove_21_0=ruleEBoolean		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getImageRule());
	        }
       		set(
       			$current, 
       			"remove",
        		lv_remove_21_0, 
        		"org.eclipse.docker.language.Container.EBoolean");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getImageAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getImageAccess().getUnorderedGroup_3(), 9)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getImageAccess().getUnorderedGroup_3(), 9);
	 				}
					({true}?=>(	otherlv_22='quiet' 
    {
    	newLeafNode(otherlv_22, grammarAccess.getImageAccess().getQuietKeyword_3_9_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getImageAccess().getQuietEBooleanParserRuleCall_3_9_1_0()); 
	    }
		lv_quiet_23_0=ruleEBoolean		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getImageRule());
	        }
       		set(
       			$current, 
       			"quiet",
        		lv_quiet_23_0, 
        		"org.eclipse.docker.language.Container.EBoolean");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getImageAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getImageAccess().getUnorderedGroup_3(), 10)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getImageAccess().getUnorderedGroup_3(), 10);
	 				}
					({true}?=>(	otherlv_24='pull' 
    {
    	newLeafNode(otherlv_24, grammarAccess.getImageAccess().getPullKeyword_3_10_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getImageAccess().getPullEBooleanParserRuleCall_3_10_1_0()); 
	    }
		lv_pull_25_0=ruleEBoolean		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getImageRule());
	        }
       		set(
       			$current, 
       			"pull",
        		lv_pull_25_0, 
        		"org.eclipse.docker.language.Container.EBoolean");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getImageAccess().getUnorderedGroup_3());
	 				}
 				)
			)  

		)*	
	)
)
	{ 
	  getUnorderedGroupHelper().leave(grammarAccess.getImageAccess().getUnorderedGroup_3());
	}

)	otherlv_26='}' 
    {
    	newLeafNode(otherlv_26, grammarAccess.getImageAccess().getRightCurlyBracketKeyword_4());
    }
)
;





// Entry rule entryRuleBuildArgs
entryRuleBuildArgs returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getBuildArgsRule()); }
	 iv_ruleBuildArgs=ruleBuildArgs 
	 { $current=$iv_ruleBuildArgs.current; } 
	 EOF 
;

// Rule BuildArgs
ruleBuildArgs returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='-' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getBuildArgsAccess().getHyphenMinusKeyword_0());
    }
(
(
		lv_key_1_0=RULE_STRING
		{
			newLeafNode(lv_key_1_0, grammarAccess.getBuildArgsAccess().getKeySTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getBuildArgsRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"key",
        		lv_key_1_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)(
(
		lv_value_2_0=RULE_STRING
		{
			newLeafNode(lv_value_2_0, grammarAccess.getBuildArgsAccess().getValueSTRINGTerminalRuleCall_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getBuildArgsRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_2_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
))
;





// Entry rule entryRuleEBoolean
entryRuleEBoolean returns [String current=null] 
	:
	{ newCompositeNode(grammarAccess.getEBooleanRule()); } 
	 iv_ruleEBoolean=ruleEBoolean 
	 { $current=$iv_ruleEBoolean.current.getText(); }  
	 EOF 
;

// Rule EBoolean
ruleEBoolean returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
	kw='false' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getEBooleanAccess().getFalseKeyword_0()); 
    }

    |
	kw='true' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getEBooleanAccess().getTrueKeyword_1()); 
    }
)
    ;





// Entry rule entryRuleElong
entryRuleElong returns [String current=null] 
	:
	{ newCompositeNode(grammarAccess.getElongRule()); } 
	 iv_ruleElong=ruleElong 
	 { $current=$iv_ruleElong.current.getText(); }  
	 EOF 
;

// Rule Elong
ruleElong returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
    this_INT_0=RULE_INT    {
		$current.merge(this_INT_0);
    }

    { 
    newLeafNode(this_INT_0, grammarAccess.getElongAccess().getINTTerminalRuleCall()); 
    }

    ;





// Entry rule entryRuleContainer
entryRuleContainer returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getContainerRule()); }
	 iv_ruleContainer=ruleContainer 
	 { $current=$iv_ruleContainer.current; } 
	 EOF 
;

// Rule Container
ruleContainer returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='container' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getContainerAccess().getContainerKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getContainerAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"org.eclipse.xtext.common.Terminals.ID");
	    }

)
)	otherlv_2='{' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_2());
    }
	otherlv_3='image' 
    {
    	newLeafNode(otherlv_3, grammarAccess.getContainerAccess().getImageKeyword_3());
    }
(
(
		lv_image_4_0=RULE_STRING
		{
			newLeafNode(lv_image_4_0, grammarAccess.getContainerAccess().getImageSTRINGTerminalRuleCall_4_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"image",
        		lv_image_4_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)(

(
	{ 
	  getUnorderedGroupHelper().enter(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	}
	(
		(

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 0)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 0);
	 				}
					({true}?=>(	otherlv_6='binds' 
    {
    	newLeafNode(otherlv_6, grammarAccess.getContainerAccess().getBindsKeyword_5_0_0());
    }
	otherlv_7='{' 
    {
    	newLeafNode(otherlv_7, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_0_1());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getBindsBindParserRuleCall_5_0_2_0()); 
	    }
		lv_binds_8_0=ruleBind		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		add(
       			$current, 
       			"binds",
        		lv_binds_8_0, 
        		"org.eclipse.docker.language.Container.Bind");
	        afterParserOrEnumRuleCall();
	    }

)
)+	otherlv_9='}' 
    {
    	newLeafNode(otherlv_9, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_0_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 1)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 1);
	 				}
					({true}?=>(	otherlv_10='capabilityAdd' 
    {
    	newLeafNode(otherlv_10, grammarAccess.getContainerAccess().getCapabilityAddKeyword_5_1_0());
    }
	otherlv_11='{' 
    {
    	newLeafNode(otherlv_11, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_1_1());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getCapabilityAddCapabilityEnumRuleCall_5_1_2_0()); 
	    }
		lv_capabilityAdd_12_0=ruleCapability		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		add(
       			$current, 
       			"capabilityAdd",
        		lv_capabilityAdd_12_0, 
        		"org.eclipse.docker.language.Container.Capability");
	        afterParserOrEnumRuleCall();
	    }

)
)+	otherlv_13='}' 
    {
    	newLeafNode(otherlv_13, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_1_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 2)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 2);
	 				}
					({true}?=>(	otherlv_14='capabilityDrop' 
    {
    	newLeafNode(otherlv_14, grammarAccess.getContainerAccess().getCapabilityDropKeyword_5_2_0());
    }
	otherlv_15='{' 
    {
    	newLeafNode(otherlv_15, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_2_1());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getCapabilityDropCapabilityEnumRuleCall_5_2_2_0()); 
	    }
		lv_capabilityDrop_16_0=ruleCapability		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		add(
       			$current, 
       			"capabilityDrop",
        		lv_capabilityDrop_16_0, 
        		"org.eclipse.docker.language.Container.Capability");
	        afterParserOrEnumRuleCall();
	    }

)
)+	otherlv_17='}' 
    {
    	newLeafNode(otherlv_17, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_2_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 3)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 3);
	 				}
					({true}?=>(	otherlv_18='commands' 
    {
    	newLeafNode(otherlv_18, grammarAccess.getContainerAccess().getCommandsKeyword_5_3_0());
    }
	otherlv_19='{' 
    {
    	newLeafNode(otherlv_19, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_3_1());
    }
(
(
		lv_commands_20_0=RULE_STRING
		{
			newLeafNode(lv_commands_20_0, grammarAccess.getContainerAccess().getCommandsSTRINGTerminalRuleCall_5_3_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		addWithLastConsumed(
       			$current, 
       			"commands",
        		lv_commands_20_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)+	otherlv_21='}' 
    {
    	newLeafNode(otherlv_21, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_3_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 4)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 4);
	 				}
					({true}?=>(	otherlv_22='containerIDFile' 
    {
    	newLeafNode(otherlv_22, grammarAccess.getContainerAccess().getContainerIDFileKeyword_5_4_0());
    }
(
(
		lv_containerIDFile_23_0=RULE_STRING
		{
			newLeafNode(lv_containerIDFile_23_0, grammarAccess.getContainerAccess().getContainerIDFileSTRINGTerminalRuleCall_5_4_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"containerIDFile",
        		lv_containerIDFile_23_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 5)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 5);
	 				}
					({true}?=>(	otherlv_24='cpuPeriod' 
    {
    	newLeafNode(otherlv_24, grammarAccess.getContainerAccess().getCpuPeriodKeyword_5_5_0());
    }
(
(
		lv_cpuPeriod_25_0=RULE_INT
		{
			newLeafNode(lv_cpuPeriod_25_0, grammarAccess.getContainerAccess().getCpuPeriodINTTerminalRuleCall_5_5_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"cpuPeriod",
        		lv_cpuPeriod_25_0, 
        		"org.eclipse.xtext.common.Terminals.INT");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 6)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 6);
	 				}
					({true}?=>(	otherlv_26='cpusetCpus' 
    {
    	newLeafNode(otherlv_26, grammarAccess.getContainerAccess().getCpusetCpusKeyword_5_6_0());
    }
(
(
		lv_cpusetCpus_27_0=RULE_STRING
		{
			newLeafNode(lv_cpusetCpus_27_0, grammarAccess.getContainerAccess().getCpusetCpusSTRINGTerminalRuleCall_5_6_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"cpusetCpus",
        		lv_cpusetCpus_27_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 7)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 7);
	 				}
					({true}?=>(	otherlv_28='cpusetMems' 
    {
    	newLeafNode(otherlv_28, grammarAccess.getContainerAccess().getCpusetMemsKeyword_5_7_0());
    }
(
(
		lv_cpusetMems_29_0=RULE_STRING
		{
			newLeafNode(lv_cpusetMems_29_0, grammarAccess.getContainerAccess().getCpusetMemsSTRINGTerminalRuleCall_5_7_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"cpusetMems",
        		lv_cpusetMems_29_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 8)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 8);
	 				}
					({true}?=>(	otherlv_30='cpuShares' 
    {
    	newLeafNode(otherlv_30, grammarAccess.getContainerAccess().getCpuSharesKeyword_5_8_0());
    }
(
(
		lv_cpuShares_31_0=RULE_INT
		{
			newLeafNode(lv_cpuShares_31_0, grammarAccess.getContainerAccess().getCpuSharesINTTerminalRuleCall_5_8_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"cpuShares",
        		lv_cpuShares_31_0, 
        		"org.eclipse.xtext.common.Terminals.INT");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 9)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 9);
	 				}
					({true}?=>(	otherlv_32='devices' 
    {
    	newLeafNode(otherlv_32, grammarAccess.getContainerAccess().getDevicesKeyword_5_9_0());
    }
	otherlv_33='{' 
    {
    	newLeafNode(otherlv_33, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_9_1());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getDevicesDeviceParserRuleCall_5_9_2_0()); 
	    }
		lv_devices_34_0=ruleDevice		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		add(
       			$current, 
       			"devices",
        		lv_devices_34_0, 
        		"org.eclipse.docker.language.Container.Device");
	        afterParserOrEnumRuleCall();
	    }

)
)+	otherlv_35='}' 
    {
    	newLeafNode(otherlv_35, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_9_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 10)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 10);
	 				}
					({true}?=>(	otherlv_36='dns' 
    {
    	newLeafNode(otherlv_36, grammarAccess.getContainerAccess().getDnsKeyword_5_10_0());
    }
(
(
		lv_dns_37_0=RULE_STRING
		{
			newLeafNode(lv_dns_37_0, grammarAccess.getContainerAccess().getDnsSTRINGTerminalRuleCall_5_10_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		addWithLastConsumed(
       			$current, 
       			"dns",
        		lv_dns_37_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)+	otherlv_38='}' 
    {
    	newLeafNode(otherlv_38, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_10_2());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 11)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 11);
	 				}
					({true}?=>(	otherlv_39='dnsSearch' 
    {
    	newLeafNode(otherlv_39, grammarAccess.getContainerAccess().getDnsSearchKeyword_5_11_0());
    }
	otherlv_40='{' 
    {
    	newLeafNode(otherlv_40, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_11_1());
    }
(
(
		lv_dnsSearch_41_0=RULE_STRING
		{
			newLeafNode(lv_dnsSearch_41_0, grammarAccess.getContainerAccess().getDnsSearchSTRINGTerminalRuleCall_5_11_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		addWithLastConsumed(
       			$current, 
       			"dnsSearch",
        		lv_dnsSearch_41_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)+	otherlv_42='}' 
    {
    	newLeafNode(otherlv_42, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_11_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 12)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 12);
	 				}
					({true}?=>(	otherlv_43='domainName' 
    {
    	newLeafNode(otherlv_43, grammarAccess.getContainerAccess().getDomainNameKeyword_5_12_0());
    }
(
(
		lv_domainName_44_0=RULE_STRING
		{
			newLeafNode(lv_domainName_44_0, grammarAccess.getContainerAccess().getDomainNameSTRINGTerminalRuleCall_5_12_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"domainName",
        		lv_domainName_44_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 13)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 13);
	 				}
					({true}?=>(	otherlv_45='entrypoint' 
    {
    	newLeafNode(otherlv_45, grammarAccess.getContainerAccess().getEntrypointKeyword_5_13_0());
    }
	otherlv_46='{' 
    {
    	newLeafNode(otherlv_46, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_13_1());
    }
(
(
		lv_entrypoint_47_0=RULE_STRING
		{
			newLeafNode(lv_entrypoint_47_0, grammarAccess.getContainerAccess().getEntrypointSTRINGTerminalRuleCall_5_13_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		addWithLastConsumed(
       			$current, 
       			"entrypoint",
        		lv_entrypoint_47_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)+	otherlv_48='}' 
    {
    	newLeafNode(otherlv_48, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_13_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 14)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 14);
	 				}
					({true}?=>(	otherlv_49='env' 
    {
    	newLeafNode(otherlv_49, grammarAccess.getContainerAccess().getEnvKeyword_5_14_0());
    }
	otherlv_50='{' 
    {
    	newLeafNode(otherlv_50, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_14_1());
    }
(
(
		lv_env_51_0=RULE_STRING
		{
			newLeafNode(lv_env_51_0, grammarAccess.getContainerAccess().getEnvSTRINGTerminalRuleCall_5_14_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		addWithLastConsumed(
       			$current, 
       			"env",
        		lv_env_51_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)+	otherlv_52='}' 
    {
    	newLeafNode(otherlv_52, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_14_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 15)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 15);
	 				}
					({true}?=>(	otherlv_53='exposedPorts' 
    {
    	newLeafNode(otherlv_53, grammarAccess.getContainerAccess().getExposedPortsKeyword_5_15_0());
    }
	otherlv_54='{' 
    {
    	newLeafNode(otherlv_54, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_15_1());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getExposedPortsExposedPortParserRuleCall_5_15_2_0()); 
	    }
		lv_exposedPorts_55_0=ruleExposedPort		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		add(
       			$current, 
       			"exposedPorts",
        		lv_exposedPorts_55_0, 
        		"org.eclipse.docker.language.Container.ExposedPort");
	        afterParserOrEnumRuleCall();
	    }

)
)+	otherlv_56='}' 
    {
    	newLeafNode(otherlv_56, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_15_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 16)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 16);
	 				}
					({true}?=>(	otherlv_57='extraHosts' 
    {
    	newLeafNode(otherlv_57, grammarAccess.getContainerAccess().getExtraHostsKeyword_5_16_0());
    }
	otherlv_58='{' 
    {
    	newLeafNode(otherlv_58, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_16_1());
    }
(
(
		lv_extraHosts_59_0=RULE_STRING
		{
			newLeafNode(lv_extraHosts_59_0, grammarAccess.getContainerAccess().getExtraHostsSTRINGTerminalRuleCall_5_16_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		addWithLastConsumed(
       			$current, 
       			"extraHosts",
        		lv_extraHosts_59_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)+	otherlv_60='}' 
    {
    	newLeafNode(otherlv_60, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_16_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 17)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 17);
	 				}
					({true}?=>(	otherlv_61='labels' 
    {
    	newLeafNode(otherlv_61, grammarAccess.getContainerAccess().getLabelsKeyword_5_17_0());
    }
	otherlv_62='{' 
    {
    	newLeafNode(otherlv_62, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_17_1());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getLabelsLabelParserRuleCall_5_17_2_0()); 
	    }
		lv_labels_63_0=ruleLabel		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		add(
       			$current, 
       			"labels",
        		lv_labels_63_0, 
        		"org.eclipse.docker.language.Container.Label");
	        afterParserOrEnumRuleCall();
	    }

)
)+	otherlv_64='}' 
    {
    	newLeafNode(otherlv_64, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_17_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 18)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 18);
	 				}
					({true}?=>(	otherlv_65='links' 
    {
    	newLeafNode(otherlv_65, grammarAccess.getContainerAccess().getLinksKeyword_5_18_0());
    }
	otherlv_66='{' 
    {
    	newLeafNode(otherlv_66, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_18_1());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getLinksLinkParserRuleCall_5_18_2_0()); 
	    }
		lv_links_67_0=ruleLink		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		add(
       			$current, 
       			"links",
        		lv_links_67_0, 
        		"org.eclipse.docker.language.Container.Link");
	        afterParserOrEnumRuleCall();
	    }

)
)+	otherlv_68='}' 
    {
    	newLeafNode(otherlv_68, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_18_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 19)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 19);
	 				}
					({true}?=>(	otherlv_69='macAddress' 
    {
    	newLeafNode(otherlv_69, grammarAccess.getContainerAccess().getMacAddressKeyword_5_19_0());
    }
(
(
		lv_macAddress_70_0=RULE_STRING
		{
			newLeafNode(lv_macAddress_70_0, grammarAccess.getContainerAccess().getMacAddressSTRINGTerminalRuleCall_5_19_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"macAddress",
        		lv_macAddress_70_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 20)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 20);
	 				}
					({true}?=>(	otherlv_71='memory' 
    {
    	newLeafNode(otherlv_71, grammarAccess.getContainerAccess().getMemoryKeyword_5_20_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getMemoryElongParserRuleCall_5_20_1_0()); 
	    }
		lv_memory_72_0=ruleElong		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		set(
       			$current, 
       			"memory",
        		lv_memory_72_0, 
        		"org.eclipse.docker.language.Container.Elong");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 21)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 21);
	 				}
					({true}?=>(	otherlv_73='memorySwap' 
    {
    	newLeafNode(otherlv_73, grammarAccess.getContainerAccess().getMemorySwapKeyword_5_21_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getMemorySwapElongParserRuleCall_5_21_1_0()); 
	    }
		lv_memorySwap_74_0=ruleElong		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		set(
       			$current, 
       			"memorySwap",
        		lv_memorySwap_74_0, 
        		"org.eclipse.docker.language.Container.Elong");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 22)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 22);
	 				}
					({true}?=>(	otherlv_75='disableNetwork' 
    {
    	newLeafNode(otherlv_75, grammarAccess.getContainerAccess().getDisableNetworkKeyword_5_22_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getDisableNetworkEBooleanParserRuleCall_5_22_1_0()); 
	    }
		lv_disableNetwork_76_0=ruleEBoolean		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		set(
       			$current, 
       			"disableNetwork",
        		lv_disableNetwork_76_0, 
        		"org.eclipse.docker.language.Container.EBoolean");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 23)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 23);
	 				}
					({true}?=>(	otherlv_77='networkMode' 
    {
    	newLeafNode(otherlv_77, grammarAccess.getContainerAccess().getNetworkModeKeyword_5_23_0());
    }
(
(
		lv_networkMode_78_0=RULE_STRING
		{
			newLeafNode(lv_networkMode_78_0, grammarAccess.getContainerAccess().getNetworkModeSTRINGTerminalRuleCall_5_23_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"networkMode",
        		lv_networkMode_78_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 24)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 24);
	 				}
					({true}?=>(	otherlv_79='portBindings' 
    {
    	newLeafNode(otherlv_79, grammarAccess.getContainerAccess().getPortBindingsKeyword_5_24_0());
    }
	otherlv_80='{' 
    {
    	newLeafNode(otherlv_80, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_24_1());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getPortBindingsPortBindingParserRuleCall_5_24_2_0()); 
	    }
		lv_portBindings_81_0=rulePortBinding		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		add(
       			$current, 
       			"portBindings",
        		lv_portBindings_81_0, 
        		"org.eclipse.docker.language.Container.PortBinding");
	        afterParserOrEnumRuleCall();
	    }

)
)+	otherlv_82='}' 
    {
    	newLeafNode(otherlv_82, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_24_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 25)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 25);
	 				}
					({true}?=>(	otherlv_83='privileged' 
    {
    	newLeafNode(otherlv_83, grammarAccess.getContainerAccess().getPrivilegedKeyword_5_25_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getPrivilegedEBooleanParserRuleCall_5_25_1_0()); 
	    }
		lv_privileged_84_0=ruleEBoolean		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		set(
       			$current, 
       			"privileged",
        		lv_privileged_84_0, 
        		"org.eclipse.docker.language.Container.EBoolean");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 26)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 26);
	 				}
					({true}?=>(	otherlv_85='publishAllPorts' 
    {
    	newLeafNode(otherlv_85, grammarAccess.getContainerAccess().getPublishAllPortsKeyword_5_26_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getPublishAllPortsEBooleanParserRuleCall_5_26_1_0()); 
	    }
		lv_publishAllPorts_86_0=ruleEBoolean		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		set(
       			$current, 
       			"publishAllPorts",
        		lv_publishAllPorts_86_0, 
        		"org.eclipse.docker.language.Container.EBoolean");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 27)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 27);
	 				}
					({true}?=>(	otherlv_87='readonlyRootfs' 
    {
    	newLeafNode(otherlv_87, grammarAccess.getContainerAccess().getReadonlyRootfsKeyword_5_27_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getReadonlyRootfsEBooleanParserRuleCall_5_27_1_0()); 
	    }
		lv_readonlyRootfs_88_0=ruleEBoolean		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		set(
       			$current, 
       			"readonlyRootfs",
        		lv_readonlyRootfs_88_0, 
        		"org.eclipse.docker.language.Container.EBoolean");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 28)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 28);
	 				}
					({true}?=>(	otherlv_89='pidMode' 
    {
    	newLeafNode(otherlv_89, grammarAccess.getContainerAccess().getPidModeKeyword_5_28_0());
    }
(
(
		lv_pidMode_90_0=RULE_STRING
		{
			newLeafNode(lv_pidMode_90_0, grammarAccess.getContainerAccess().getPidModeSTRINGTerminalRuleCall_5_28_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"pidMode",
        		lv_pidMode_90_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 29)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 29);
	 				}
					({true}?=>(	otherlv_91='workingDir' 
    {
    	newLeafNode(otherlv_91, grammarAccess.getContainerAccess().getWorkingDirKeyword_5_29_0());
    }
(
(
		lv_workingDir_92_0=RULE_STRING
		{
			newLeafNode(lv_workingDir_92_0, grammarAccess.getContainerAccess().getWorkingDirSTRINGTerminalRuleCall_5_29_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"workingDir",
        		lv_workingDir_92_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 30)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 30);
	 				}
					({true}?=>(	otherlv_93='user' 
    {
    	newLeafNode(otherlv_93, grammarAccess.getContainerAccess().getUserKeyword_5_30_0());
    }
(
(
		lv_user_94_0=RULE_STRING
		{
			newLeafNode(lv_user_94_0, grammarAccess.getContainerAccess().getUserSTRINGTerminalRuleCall_5_30_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getContainerRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"user",
        		lv_user_94_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 31)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 31);
	 				}
					({true}?=>(	otherlv_95='tty' 
    {
    	newLeafNode(otherlv_95, grammarAccess.getContainerAccess().getTtyKeyword_5_31_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getTtyEBooleanParserRuleCall_5_31_1_0()); 
	    }
		lv_tty_96_0=ruleEBoolean		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		set(
       			$current, 
       			"tty",
        		lv_tty_96_0, 
        		"org.eclipse.docker.language.Container.EBoolean");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 32)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 32);
	 				}
					({true}?=>(	otherlv_97='restartPolicy' 
    {
    	newLeafNode(otherlv_97, grammarAccess.getContainerAccess().getRestartPolicyKeyword_5_32_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getRestartPolicyRestartPolicyParserRuleCall_5_32_1_0()); 
	    }
		lv_restartPolicy_98_0=ruleRestartPolicy		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		set(
       			$current, 
       			"restartPolicy",
        		lv_restartPolicy_98_0, 
        		"org.eclipse.docker.language.Container.RestartPolicy");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 33)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 33);
	 				}
					({true}?=>(	otherlv_99='volumes' 
    {
    	newLeafNode(otherlv_99, grammarAccess.getContainerAccess().getVolumesKeyword_5_33_0());
    }
	otherlv_100='{' 
    {
    	newLeafNode(otherlv_100, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_33_1());
    }
(	otherlv_101='-' 
    {
    	newLeafNode(otherlv_101, grammarAccess.getContainerAccess().getHyphenMinusKeyword_5_33_2_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getVolumesVolumeParserRuleCall_5_33_2_1_0()); 
	    }
		lv_volumes_102_0=ruleVolume		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		add(
       			$current, 
       			"volumes",
        		lv_volumes_102_0, 
        		"org.eclipse.docker.language.Container.Volume");
	        afterParserOrEnumRuleCall();
	    }

)
))+	otherlv_103='}' 
    {
    	newLeafNode(otherlv_103, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_33_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 34)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 34);
	 				}
					({true}?=>(	otherlv_104='volumesFrom' 
    {
    	newLeafNode(otherlv_104, grammarAccess.getContainerAccess().getVolumesFromKeyword_5_34_0());
    }
	otherlv_105='{' 
    {
    	newLeafNode(otherlv_105, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_34_1());
    }
(	otherlv_106='-' 
    {
    	newLeafNode(otherlv_106, grammarAccess.getContainerAccess().getHyphenMinusKeyword_5_34_2_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getVolumesFromVolumesFromParserRuleCall_5_34_2_1_0()); 
	    }
		lv_volumesFrom_107_0=ruleVolumesFrom		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		add(
       			$current, 
       			"volumesFrom",
        		lv_volumesFrom_107_0, 
        		"org.eclipse.docker.language.Container.VolumesFrom");
	        afterParserOrEnumRuleCall();
	    }

)
))+	otherlv_108='}' 
    {
    	newLeafNode(otherlv_108, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_34_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 35)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getContainerAccess().getUnorderedGroup_5(), 35);
	 				}
					({true}?=>(	otherlv_109='ulimits' 
    {
    	newLeafNode(otherlv_109, grammarAccess.getContainerAccess().getUlimitsKeyword_5_35_0());
    }
	otherlv_110='{' 
    {
    	newLeafNode(otherlv_110, grammarAccess.getContainerAccess().getLeftCurlyBracketKeyword_5_35_1());
    }
(	otherlv_111='-' 
    {
    	newLeafNode(otherlv_111, grammarAccess.getContainerAccess().getHyphenMinusKeyword_5_35_2_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getContainerAccess().getUlimitsUlimitParserRuleCall_5_35_2_1_0()); 
	    }
		lv_ulimits_112_0=ruleUlimit		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getContainerRule());
	        }
       		add(
       			$current, 
       			"ulimits",
        		lv_ulimits_112_0, 
        		"org.eclipse.docker.language.Container.Ulimit");
	        afterParserOrEnumRuleCall();
	    }

)
))+	otherlv_113='}' 
    {
    	newLeafNode(otherlv_113, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_5_35_3());
    }
))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	 				}
 				)
			)  

		)*	
	)
)
	{ 
	  getUnorderedGroupHelper().leave(grammarAccess.getContainerAccess().getUnorderedGroup_5());
	}

)	otherlv_114='}' 
    {
    	newLeafNode(otherlv_114, grammarAccess.getContainerAccess().getRightCurlyBracketKeyword_6());
    }
)
;





// Entry rule entryRuleVolumesFrom
entryRuleVolumesFrom returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getVolumesFromRule()); }
	 iv_ruleVolumesFrom=ruleVolumesFrom 
	 { $current=$iv_ruleVolumesFrom.current; } 
	 EOF 
;

// Rule VolumesFrom
ruleVolumesFrom returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='-' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getVolumesFromAccess().getHyphenMinusKeyword_0());
    }
(
(
		lv_container_1_0=RULE_STRING
		{
			newLeafNode(lv_container_1_0, grammarAccess.getVolumesFromAccess().getContainerSTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getVolumesFromRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"container",
        		lv_container_1_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)	otherlv_2=':' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getVolumesFromAccess().getColonKeyword_2());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getVolumesFromAccess().getAccessModeAccessModeEnumRuleCall_3_0()); 
	    }
		lv_accessMode_3_0=ruleAccessMode		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getVolumesFromRule());
	        }
       		set(
       			$current, 
       			"accessMode",
        		lv_accessMode_3_0, 
        		"org.eclipse.docker.language.Container.AccessMode");
	        afterParserOrEnumRuleCall();
	    }

)
)?)
;





// Entry rule entryRuleRestartPolicy
entryRuleRestartPolicy returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getRestartPolicyRule()); }
	 iv_ruleRestartPolicy=ruleRestartPolicy 
	 { $current=$iv_ruleRestartPolicy.current; } 
	 EOF 
;

// Rule RestartPolicy
ruleRestartPolicy returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
((	otherlv_0='-' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getRestartPolicyAccess().getHyphenMinusKeyword_0_0());
    }
(
(
		lv_value_1_0=	'always' 
    {
        newLeafNode(lv_value_1_0, grammarAccess.getRestartPolicyAccess().getValueAlwaysKeyword_0_1_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getRestartPolicyRule());
	        }
       		setWithLastConsumed($current, "value", lv_value_1_0, "always");
	    }

)
))
    |	otherlv_2='onFailure' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getRestartPolicyAccess().getOnFailureKeyword_1());
    }

    |(	otherlv_3='none' 
    {
    	newLeafNode(otherlv_3, grammarAccess.getRestartPolicyAccess().getNoneKeyword_2_0());
    }
(
(
		lv_maximumRetryCount_4_0=RULE_INT
		{
			newLeafNode(lv_maximumRetryCount_4_0, grammarAccess.getRestartPolicyAccess().getMaximumRetryCountINTTerminalRuleCall_2_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getRestartPolicyRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"maximumRetryCount",
        		lv_maximumRetryCount_4_0, 
        		"org.eclipse.xtext.common.Terminals.INT");
	    }

)
)))
;





// Entry rule entryRulePortBinding
entryRulePortBinding returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getPortBindingRule()); }
	 iv_rulePortBinding=rulePortBinding 
	 { $current=$iv_rulePortBinding.current; } 
	 EOF 
;

// Rule PortBinding
rulePortBinding returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='-' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getPortBindingAccess().getHyphenMinusKeyword_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getPortBindingAccess().getBindingBindingParserRuleCall_1_0()); 
	    }
		lv_binding_1_0=ruleBinding		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getPortBindingRule());
	        }
       		set(
       			$current, 
       			"binding",
        		lv_binding_1_0, 
        		"org.eclipse.docker.language.Container.Binding");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getPortBindingRule());
	        }
        }
	otherlv_2=RULE_STRING
	{
		newLeafNode(otherlv_2, grammarAccess.getPortBindingAccess().getExposedPortExposedPortCrossReference_2_0()); 
	}

)
))
;





// Entry rule entryRuleBinding
entryRuleBinding returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getBindingRule()); }
	 iv_ruleBinding=ruleBinding 
	 { $current=$iv_ruleBinding.current; } 
	 EOF 
;

// Rule Binding
ruleBinding returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='-' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getBindingAccess().getHyphenMinusKeyword_0());
    }
(
(
		lv_hostIP_1_0=RULE_STRING
		{
			newLeafNode(lv_hostIP_1_0, grammarAccess.getBindingAccess().getHostIPSTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getBindingRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"hostIP",
        		lv_hostIP_1_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)	otherlv_2=':' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getBindingAccess().getColonKeyword_2());
    }
(
(
		lv_hostPort_3_0=RULE_INT
		{
			newLeafNode(lv_hostPort_3_0, grammarAccess.getBindingAccess().getHostPortINTTerminalRuleCall_3_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getBindingRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"hostPort",
        		lv_hostPort_3_0, 
        		"org.eclipse.xtext.common.Terminals.INT");
	    }

)
))
;





// Entry rule entryRuleLink
entryRuleLink returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getLinkRule()); }
	 iv_ruleLink=ruleLink 
	 { $current=$iv_ruleLink.current; } 
	 EOF 
;

// Rule Link
ruleLink returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='-' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getLinkAccess().getHyphenMinusKeyword_0());
    }
(
(
		lv_containerLink_1_0=RULE_STRING
		{
			newLeafNode(lv_containerLink_1_0, grammarAccess.getLinkAccess().getContainerLinkSTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getLinkRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"containerLink",
        		lv_containerLink_1_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)	otherlv_2=':' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getLinkAccess().getColonKeyword_2());
    }
(
(
		lv_alias_3_0=RULE_STRING
		{
			newLeafNode(lv_alias_3_0, grammarAccess.getLinkAccess().getAliasSTRINGTerminalRuleCall_3_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getLinkRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"alias",
        		lv_alias_3_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
))
;





// Entry rule entryRuleUlimit
entryRuleUlimit returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getUlimitRule()); }
	 iv_ruleUlimit=ruleUlimit 
	 { $current=$iv_ruleUlimit.current; } 
	 EOF 
;

// Rule Ulimit
ruleUlimit returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='-' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getUlimitAccess().getHyphenMinusKeyword_0());
    }
(
(
		lv_name_1_0=RULE_STRING
		{
			newLeafNode(lv_name_1_0, grammarAccess.getUlimitAccess().getNameSTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getUlimitRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)(
(
		lv_soft_2_0=RULE_INT
		{
			newLeafNode(lv_soft_2_0, grammarAccess.getUlimitAccess().getSoftINTTerminalRuleCall_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getUlimitRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"soft",
        		lv_soft_2_0, 
        		"org.eclipse.xtext.common.Terminals.INT");
	    }

)
)(
(
		lv_hard_3_0=RULE_INT
		{
			newLeafNode(lv_hard_3_0, grammarAccess.getUlimitAccess().getHardINTTerminalRuleCall_3_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getUlimitRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"hard",
        		lv_hard_3_0, 
        		"org.eclipse.xtext.common.Terminals.INT");
	    }

)
))
;





// Entry rule entryRuleLabel
entryRuleLabel returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getLabelRule()); }
	 iv_ruleLabel=ruleLabel 
	 { $current=$iv_ruleLabel.current; } 
	 EOF 
;

// Rule Label
ruleLabel returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
((
(
		lv_key_0_0=RULE_STRING
		{
			newLeafNode(lv_key_0_0, grammarAccess.getLabelAccess().getKeySTRINGTerminalRuleCall_0_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getLabelRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"key",
        		lv_key_0_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)(
(
		lv_value_1_0=RULE_STRING
		{
			newLeafNode(lv_value_1_0, grammarAccess.getLabelAccess().getValueSTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getLabelRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
))
;





// Entry rule entryRuleExposedPort
entryRuleExposedPort returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getExposedPortRule()); }
	 iv_ruleExposedPort=ruleExposedPort 
	 { $current=$iv_ruleExposedPort.current; } 
	 EOF 
;

// Rule ExposedPort
ruleExposedPort returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='-' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getExposedPortAccess().getHyphenMinusKeyword_0());
    }
(
(
		lv_port_1_0=RULE_STRING
		{
			newLeafNode(lv_port_1_0, grammarAccess.getExposedPortAccess().getPortSTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getExposedPortRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"port",
        		lv_port_1_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)	otherlv_2='/' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getExposedPortAccess().getSolidusKeyword_2());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getExposedPortAccess().getProtocolInternalProtocolEnumRuleCall_3_0()); 
	    }
		lv_protocol_3_0=ruleInternalProtocol		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getExposedPortRule());
	        }
       		set(
       			$current, 
       			"protocol",
        		lv_protocol_3_0, 
        		"org.eclipse.docker.language.Container.InternalProtocol");
	        afterParserOrEnumRuleCall();
	    }

)
))
;





// Entry rule entryRuleDevice
entryRuleDevice returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getDeviceRule()); }
	 iv_ruleDevice=ruleDevice 
	 { $current=$iv_ruleDevice.current; } 
	 EOF 
;

// Rule Device
ruleDevice returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='-' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getDeviceAccess().getHyphenMinusKeyword_0());
    }
(
(
		lv_cGroupPermissions_1_0=RULE_STRING
		{
			newLeafNode(lv_cGroupPermissions_1_0, grammarAccess.getDeviceAccess().getCGroupPermissionsSTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getDeviceRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"cGroupPermissions",
        		lv_cGroupPermissions_1_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)(
(
		lv_pathOnHost_2_0=RULE_STRING
		{
			newLeafNode(lv_pathOnHost_2_0, grammarAccess.getDeviceAccess().getPathOnHostSTRINGTerminalRuleCall_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getDeviceRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"pathOnHost",
        		lv_pathOnHost_2_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)(
(
		lv_pathInContainer_3_0=RULE_STRING
		{
			newLeafNode(lv_pathInContainer_3_0, grammarAccess.getDeviceAccess().getPathInContainerSTRINGTerminalRuleCall_3_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getDeviceRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"pathInContainer",
        		lv_pathInContainer_3_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
))
;





// Entry rule entryRuleBind
entryRuleBind returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getBindRule()); }
	 iv_ruleBind=ruleBind 
	 { $current=$iv_ruleBind.current; } 
	 EOF 
;

// Rule Bind
ruleBind returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='-' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getBindAccess().getHyphenMinusKeyword_0());
    }
(
(
		lv_location_1_0=RULE_STRING
		{
			newLeafNode(lv_location_1_0, grammarAccess.getBindAccess().getLocationSTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getBindRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"location",
        		lv_location_1_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)	otherlv_2=':' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getBindAccess().getColonKeyword_2());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getBindAccess().getVolumeVolumeParserRuleCall_3_0()); 
	    }
		lv_volume_3_0=ruleVolume		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getBindRule());
	        }
       		set(
       			$current, 
       			"volume",
        		lv_volume_3_0, 
        		"org.eclipse.docker.language.Container.Volume");
	        afterParserOrEnumRuleCall();
	    }

)
)(	otherlv_4=':' 
    {
    	newLeafNode(otherlv_4, grammarAccess.getBindAccess().getColonKeyword_4_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getBindAccess().getAccessMode1AccessModeEnumRuleCall_4_1_0()); 
	    }
		lv_accessMode1_5_0=ruleAccessMode		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getBindRule());
	        }
       		set(
       			$current, 
       			"accessMode1",
        		lv_accessMode1_5_0, 
        		"org.eclipse.docker.language.Container.AccessMode");
	        afterParserOrEnumRuleCall();
	    }

)
))?)
;





// Entry rule entryRuleVolume
entryRuleVolume returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getVolumeRule()); }
	 iv_ruleVolume=ruleVolume 
	 { $current=$iv_ruleVolume.current; } 
	 EOF 
;

// Rule Volume
ruleVolume returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
(
		lv_path_0_0=RULE_STRING
		{
			newLeafNode(lv_path_0_0, grammarAccess.getVolumeAccess().getPathSTRINGTerminalRuleCall_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getVolumeRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"path",
        		lv_path_0_0, 
        		"org.eclipse.xtext.common.Terminals.STRING");
	    }

)
)
;





// Rule InternalProtocol
ruleInternalProtocol returns [Enumerator current=null] 
    @init { enterRule(); }
    @after { leaveRule(); }:
((	enumLiteral_0='TCP' 
	{
        $current = grammarAccess.getInternalProtocolAccess().getTCPEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_0, grammarAccess.getInternalProtocolAccess().getTCPEnumLiteralDeclaration_0()); 
    }
)
    |(	enumLiteral_1='UDP' 
	{
        $current = grammarAccess.getInternalProtocolAccess().getUDPEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_1, grammarAccess.getInternalProtocolAccess().getUDPEnumLiteralDeclaration_1()); 
    }
));



// Rule AccessMode
ruleAccessMode returns [Enumerator current=null] 
    @init { enterRule(); }
    @after { leaveRule(); }:
((	enumLiteral_0='rw' 
	{
        $current = grammarAccess.getAccessModeAccess().getRwEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_0, grammarAccess.getAccessModeAccess().getRwEnumLiteralDeclaration_0()); 
    }
)
    |(	enumLiteral_1='ro' 
	{
        $current = grammarAccess.getAccessModeAccess().getRoEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_1, grammarAccess.getAccessModeAccess().getRoEnumLiteralDeclaration_1()); 
    }
));



// Rule Capability
ruleCapability returns [Enumerator current=null] 
    @init { enterRule(); }
    @after { leaveRule(); }:
((	enumLiteral_0='ALL' 
	{
        $current = grammarAccess.getCapabilityAccess().getALLEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_0, grammarAccess.getCapabilityAccess().getALLEnumLiteralDeclaration_0()); 
    }
)
    |(	enumLiteral_1='AUDIT_CONTROL' 
	{
        $current = grammarAccess.getCapabilityAccess().getAUDIT_CONTROLEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_1, grammarAccess.getCapabilityAccess().getAUDIT_CONTROLEnumLiteralDeclaration_1()); 
    }
)
    |(	enumLiteral_2='AUDIT_WRITE' 
	{
        $current = grammarAccess.getCapabilityAccess().getAUDIT_WRITEEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_2, grammarAccess.getCapabilityAccess().getAUDIT_WRITEEnumLiteralDeclaration_2()); 
    }
)
    |(	enumLiteral_3='BLOCK_SUSPEND' 
	{
        $current = grammarAccess.getCapabilityAccess().getBLOCK_SUSPENDEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_3, grammarAccess.getCapabilityAccess().getBLOCK_SUSPENDEnumLiteralDeclaration_3()); 
    }
)
    |(	enumLiteral_4='CHOWN' 
	{
        $current = grammarAccess.getCapabilityAccess().getCHOWNEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_4, grammarAccess.getCapabilityAccess().getCHOWNEnumLiteralDeclaration_4()); 
    }
)
    |(	enumLiteral_5='DAC_OVERRIDE' 
	{
        $current = grammarAccess.getCapabilityAccess().getDAC_OVERRIDEEnumLiteralDeclaration_5().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_5, grammarAccess.getCapabilityAccess().getDAC_OVERRIDEEnumLiteralDeclaration_5()); 
    }
)
    |(	enumLiteral_6='DAC_READ_SEARCH' 
	{
        $current = grammarAccess.getCapabilityAccess().getDAC_READ_SEARCHEnumLiteralDeclaration_6().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_6, grammarAccess.getCapabilityAccess().getDAC_READ_SEARCHEnumLiteralDeclaration_6()); 
    }
)
    |(	enumLiteral_7='FOWNER' 
	{
        $current = grammarAccess.getCapabilityAccess().getFOWNEREnumLiteralDeclaration_7().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_7, grammarAccess.getCapabilityAccess().getFOWNEREnumLiteralDeclaration_7()); 
    }
)
    |(	enumLiteral_8='FSETID' 
	{
        $current = grammarAccess.getCapabilityAccess().getFSETIDEnumLiteralDeclaration_8().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_8, grammarAccess.getCapabilityAccess().getFSETIDEnumLiteralDeclaration_8()); 
    }
)
    |(	enumLiteral_9='IPC_LOCK' 
	{
        $current = grammarAccess.getCapabilityAccess().getIPC_LOCKEnumLiteralDeclaration_9().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_9, grammarAccess.getCapabilityAccess().getIPC_LOCKEnumLiteralDeclaration_9()); 
    }
)
    |(	enumLiteral_10='IPC_OWNER' 
	{
        $current = grammarAccess.getCapabilityAccess().getIPC_OWNEREnumLiteralDeclaration_10().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_10, grammarAccess.getCapabilityAccess().getIPC_OWNEREnumLiteralDeclaration_10()); 
    }
)
    |(	enumLiteral_11='KILL' 
	{
        $current = grammarAccess.getCapabilityAccess().getKILLEnumLiteralDeclaration_11().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_11, grammarAccess.getCapabilityAccess().getKILLEnumLiteralDeclaration_11()); 
    }
)
    |(	enumLiteral_12='LEASE' 
	{
        $current = grammarAccess.getCapabilityAccess().getLEASEEnumLiteralDeclaration_12().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_12, grammarAccess.getCapabilityAccess().getLEASEEnumLiteralDeclaration_12()); 
    }
)
    |(	enumLiteral_13='LINUX_IMMUTABLE' 
	{
        $current = grammarAccess.getCapabilityAccess().getLINUX_IMMUTABLEEnumLiteralDeclaration_13().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_13, grammarAccess.getCapabilityAccess().getLINUX_IMMUTABLEEnumLiteralDeclaration_13()); 
    }
)
    |(	enumLiteral_14='MAC_ADMIN' 
	{
        $current = grammarAccess.getCapabilityAccess().getMAC_ADMINEnumLiteralDeclaration_14().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_14, grammarAccess.getCapabilityAccess().getMAC_ADMINEnumLiteralDeclaration_14()); 
    }
)
    |(	enumLiteral_15='MAC_OVERRIDE' 
	{
        $current = grammarAccess.getCapabilityAccess().getMAC_OVERRIDEEnumLiteralDeclaration_15().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_15, grammarAccess.getCapabilityAccess().getMAC_OVERRIDEEnumLiteralDeclaration_15()); 
    }
)
    |(	enumLiteral_16='MKNOD' 
	{
        $current = grammarAccess.getCapabilityAccess().getMKNODEnumLiteralDeclaration_16().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_16, grammarAccess.getCapabilityAccess().getMKNODEnumLiteralDeclaration_16()); 
    }
)
    |(	enumLiteral_17='NET_ADMIN' 
	{
        $current = grammarAccess.getCapabilityAccess().getNET_ADMINEnumLiteralDeclaration_17().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_17, grammarAccess.getCapabilityAccess().getNET_ADMINEnumLiteralDeclaration_17()); 
    }
)
    |(	enumLiteral_18='NET_BIND_SERVICE' 
	{
        $current = grammarAccess.getCapabilityAccess().getNET_BIND_SERVICEEnumLiteralDeclaration_18().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_18, grammarAccess.getCapabilityAccess().getNET_BIND_SERVICEEnumLiteralDeclaration_18()); 
    }
)
    |(	enumLiteral_19='NET_BROADCAST' 
	{
        $current = grammarAccess.getCapabilityAccess().getNET_BROADCASTEnumLiteralDeclaration_19().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_19, grammarAccess.getCapabilityAccess().getNET_BROADCASTEnumLiteralDeclaration_19()); 
    }
)
    |(	enumLiteral_20='NET_RAW' 
	{
        $current = grammarAccess.getCapabilityAccess().getNET_RAWEnumLiteralDeclaration_20().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_20, grammarAccess.getCapabilityAccess().getNET_RAWEnumLiteralDeclaration_20()); 
    }
)
    |(	enumLiteral_21='SETFCAP' 
	{
        $current = grammarAccess.getCapabilityAccess().getSETFCAPEnumLiteralDeclaration_21().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_21, grammarAccess.getCapabilityAccess().getSETFCAPEnumLiteralDeclaration_21()); 
    }
)
    |(	enumLiteral_22='SETGID' 
	{
        $current = grammarAccess.getCapabilityAccess().getSETGIDEnumLiteralDeclaration_22().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_22, grammarAccess.getCapabilityAccess().getSETGIDEnumLiteralDeclaration_22()); 
    }
)
    |(	enumLiteral_23='SETPCAP' 
	{
        $current = grammarAccess.getCapabilityAccess().getSETPCAPEnumLiteralDeclaration_23().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_23, grammarAccess.getCapabilityAccess().getSETPCAPEnumLiteralDeclaration_23()); 
    }
)
    |(	enumLiteral_24='SETUID' 
	{
        $current = grammarAccess.getCapabilityAccess().getSETUIDEnumLiteralDeclaration_24().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_24, grammarAccess.getCapabilityAccess().getSETUIDEnumLiteralDeclaration_24()); 
    }
)
    |(	enumLiteral_25='SYS_ADMIN' 
	{
        $current = grammarAccess.getCapabilityAccess().getSYS_ADMINEnumLiteralDeclaration_25().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_25, grammarAccess.getCapabilityAccess().getSYS_ADMINEnumLiteralDeclaration_25()); 
    }
)
    |(	enumLiteral_26='SYS_BOOT' 
	{
        $current = grammarAccess.getCapabilityAccess().getSYS_BOOTEnumLiteralDeclaration_26().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_26, grammarAccess.getCapabilityAccess().getSYS_BOOTEnumLiteralDeclaration_26()); 
    }
)
    |(	enumLiteral_27='SYS_CHROOT' 
	{
        $current = grammarAccess.getCapabilityAccess().getSYS_CHROOTEnumLiteralDeclaration_27().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_27, grammarAccess.getCapabilityAccess().getSYS_CHROOTEnumLiteralDeclaration_27()); 
    }
)
    |(	enumLiteral_28='SYSLOG' 
	{
        $current = grammarAccess.getCapabilityAccess().getSYSLOGEnumLiteralDeclaration_28().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_28, grammarAccess.getCapabilityAccess().getSYSLOGEnumLiteralDeclaration_28()); 
    }
)
    |(	enumLiteral_29='SYS_MODULE' 
	{
        $current = grammarAccess.getCapabilityAccess().getSYS_MODULEEnumLiteralDeclaration_29().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_29, grammarAccess.getCapabilityAccess().getSYS_MODULEEnumLiteralDeclaration_29()); 
    }
)
    |(	enumLiteral_30='SYS_NICE' 
	{
        $current = grammarAccess.getCapabilityAccess().getSYS_NICEEnumLiteralDeclaration_30().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_30, grammarAccess.getCapabilityAccess().getSYS_NICEEnumLiteralDeclaration_30()); 
    }
)
    |(	enumLiteral_31='SYS_PACCT' 
	{
        $current = grammarAccess.getCapabilityAccess().getSYS_PACCTEnumLiteralDeclaration_31().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_31, grammarAccess.getCapabilityAccess().getSYS_PACCTEnumLiteralDeclaration_31()); 
    }
)
    |(	enumLiteral_32='SYS_PTRACE' 
	{
        $current = grammarAccess.getCapabilityAccess().getSYS_PTRACEEnumLiteralDeclaration_32().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_32, grammarAccess.getCapabilityAccess().getSYS_PTRACEEnumLiteralDeclaration_32()); 
    }
)
    |(	enumLiteral_33='SYS_RAWIO' 
	{
        $current = grammarAccess.getCapabilityAccess().getSYS_RAWIOEnumLiteralDeclaration_33().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_33, grammarAccess.getCapabilityAccess().getSYS_RAWIOEnumLiteralDeclaration_33()); 
    }
)
    |(	enumLiteral_34='SYS_RESOURCE' 
	{
        $current = grammarAccess.getCapabilityAccess().getSYS_RESOURCEEnumLiteralDeclaration_34().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_34, grammarAccess.getCapabilityAccess().getSYS_RESOURCEEnumLiteralDeclaration_34()); 
    }
)
    |(	enumLiteral_35='SYS_TIME' 
	{
        $current = grammarAccess.getCapabilityAccess().getSYS_TIMEEnumLiteralDeclaration_35().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_35, grammarAccess.getCapabilityAccess().getSYS_TIMEEnumLiteralDeclaration_35()); 
    }
)
    |(	enumLiteral_36='SYS_TTY_CONFIG' 
	{
        $current = grammarAccess.getCapabilityAccess().getSYS_TTY_CONFIGEnumLiteralDeclaration_36().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_36, grammarAccess.getCapabilityAccess().getSYS_TTY_CONFIGEnumLiteralDeclaration_36()); 
    }
)
    |(	enumLiteral_37='WAKE_ALARM' 
	{
        $current = grammarAccess.getCapabilityAccess().getWAKE_ALARMEnumLiteralDeclaration_37().getEnumLiteral().getInstance();
        newLeafNode(enumLiteral_37, grammarAccess.getCapabilityAccess().getWAKE_ALARMEnumLiteralDeclaration_37()); 
    }
));



RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;


